INSERT INTO v1_student VALUES ("1001", "Rick", "Davis", "I.T.", "Junior",3.6 );
INSERT INTO v1_student VALUES ("1002", "Miles", "Greer", "Physics", "Senior",3.8 );
INSERT INTO v1_student VALUES ("1003", "David", "Leap", "Chemistry", "Sophomore",3.7 );
INSERT INTO v1_student VALUES ("1004", "Rick", "Barry", "I.T.", "Senior",3.9 );
INSERT INTO v1_student VALUES ("1005", "Gwen", "Trask", "Physics", "Senior",3 );
INSERT INTO v1_student VALUES ("1006", "Lilly", "Steele", "Marketing", "Sophomore",3.15 );
INSERT INTO v1_student VALUES ("1007", "Damon", "Woody", "Stats", "Junior",3.3 );
INSERT INTO v1_student VALUES ("1008", "Tyus", "Sneed", "I.T.", "Junior",3.76 );
INSERT INTO v1_student VALUES ("1009", "Drew", "Little", "Stats", "Senior",3.8 );
INSERT INTO v1_student VALUES ("1010", "Maya", "Miller", "I.T.", "Junior",3.9 );
INSERT INTO v1_student VALUES ("1011", "Trent", "Davis", "I.T.", "Junior",3.6 );
INSERT INTO v1_student VALUES ("1012", "Rob", "Hale", "Physics", "Senior",3.8 );
INSERT INTO v1_student VALUES ("1013", "David", "Sync", "Chemistry", "Sophomore",3.2 );
INSERT INTO v1_student VALUES ("1014", "Eric", "Leary", "Stats", "Senior",4 );
INSERT INTO v1_student VALUES ("1015", "Anya", "Reid", "Stats", "Sophomore",3.21 );
INSERT INTO v1_student VALUES ("1016", "Derrick", "Lewis", "I.T.", "Junior",3.6 );
INSERT INTO v1_student VALUES ("1017", "Peter", "Cyriac", "Physics", "Senior",3.8 );
INSERT INTO v1_student VALUES ("1018", "Alton", "Chase", "Chemistry", "Sophomore",3.5 );
INSERT INTO v1_student VALUES ("1019", "Monica", "Monroe", "Physics", "Sophomore",3.3 );
INSERT INTO v1_student VALUES ("1020", "Abby", "Mathew", "I.T.", "Junior",4 );

INSERT INTO v1_course VALUES ("3903", "ECON 3903", "Faculty Seminar Topics in Entr", 1, "Economics","Lerner,Josh" );
INSERT INTO v1_course VALUES ("107349", "MODMDEST 100", "Intro Modern Middle East", 1, "Near Eastern Languages & Civ","Zeghal,Malika" );
INSERT INTO v1_course VALUES ("107368", "PHYSCI 11", "Frontiers of Modern Chemistry", 1, "Chemistry & Chemical Biology","Anderson,James G." );
INSERT INTO v1_course VALUES ("107375", "IT 105", "Fundamentals of I.T", 2, "I.T.","Delacy,Richard Somers" );
INSERT INTO v1_course VALUES ("107378", "SAS 100R", "South Asian Language Tutorials", 1, "South Asian Studies","Delacy,Richard Somers" );
INSERT INTO v1_course VALUES ("107380", "SAS 98R", "Tutorial - Junior Year", 1, "South Asian Studies","Delacy,Richard Somers" );
INSERT INTO v1_course VALUES ("107425", "ECON 1450", "Religion and Political Economy", 1, "Economics","Barro,Robert J." );
INSERT INTO v1_course VALUES ("107451", "PSY 1502", "Cultural Psychology", 1, "Psychology","Kimel,Sasha Y." );
INSERT INTO v1_course VALUES ("107455", "CELLBIO 307QC", "Chromatin Dynamics", 1, "Medical Sciences","Mostoslavsky,Raul" );
INSERT INTO v1_course VALUES ("107600", "APMTH 221", "Advanced Optimization", 1, "Applied Mathematics","Kyng,Rasmus" );
INSERT INTO v1_course VALUES ("107602", "PSY 1503", "Psych of Close Relationships", 1, "Psychology","Parker,Holly Ann" );
INSERT INTO v1_course VALUES ("107628", "DRB 322", "Regulation of Tissue Stem Cell", 1, "Medical Sciences","Breault,David T." );
INSERT INTO v1_course VALUES ("107630", "GENETIC 397", "Immunogenomics", 1, "Medical Sciences","Raychaudhuri,Soumya" );
INSERT INTO v1_course VALUES ("107672", "PERSIAN 152", "Persian Epic Tradition", 1, "Near Eastern Languages & Civ","Landau,Justine Karen" );
INSERT INTO v1_course VALUES ("107703", "CHEM 320", "Chemical Biology", 1, "Chemistry & Chemical Biology","Balskus,Emily Patricia" );
INSERT INTO v1_course VALUES ("107706", "PSY 2410R", "Lab Research Emotional Disorde", 1, "Psychology","McNally,Richard J." );
INSERT INTO v1_course VALUES ("107746", "NEUROBIO 355", "A Biophysical Approach to Syst", 1, "Medical Sciences","Do,Michael Tri Hoang" );
INSERT INTO v1_course VALUES ("107761", "GENETIC 395", "Regulation of global genes", 1, "Medical Sciences","Churchman,Stirling" );
INSERT INTO v1_course VALUES ("107764", "ENG-SCI 265", "Advanced Water Treatment", 1, "Engineering Sciences","Vecitis,Chad D." );
